apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ${{ values.product }}-${{ values.component }} App
name: ${{ values.product }}-${{ values.component }}
home: https://github.com/hmcts/${{ values.product }}-${{ values.component }}
version: 0.0.1
maintainers:
  - name: HMCTS ${{ values.product }} team
dependencies:
  - name: java
    version: 4.0.6
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
