apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{ cookiecutter.product }}-{{ cookiecutter.component_id }}"
  description: {{ cookiecutter.description }}
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/github-folder: 'HMCTS_{{ cookiecutter.product }}/{{ cookiecutter.product }}-{{ cookiecutter.component_id }}'
    github.com/project-slug: '{{ cookiecutter.storePath }}'
  tags:
    - Java
    - {{ cookiecutter.product }}
spec:
  type: service
  lifecycle: experimental
  owner: {{ cookiecutter.owner }}
