java:
  applicationPort: {{ cookiecutter.http_port }}
  image: 'hmctspublic.azurecr.io/{{ cookiecutter.product }}/{{ cookiecutter.component_id }}:latest'
  ingressHost: {{ cookiecutter.app_full_name }}-{{ '{{' }} .Values.global.environment {{ '}}' }}.service.core-compute-{{ '{{' }} .Values.global.environment {{ '}}' }}.internal
  aadIdentityName: {{ cookiecutter.product }}
  environment:
